version: '2'

services:
  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./sites-enabled:/etc/nginx/conf.d
      - ./html:/html
    labels:
      - "traefik.docker.network=webproxy"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:$SERVER_HOST"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"

networks:
  default:
    external:
      name: webproxy
