version: '2'

services:
  web:
    image: xataz/nginx:latest
    restart: always
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ./sites-enabled:/nginx/sites-enabled
      - ./html:/html
    labels:
      - "traefik.docker.network=webproxy"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:$SERVER_HOST"
      - "traefik.basic.port=8080"
      - "traefik.basic.protocol=http"

networks:
  default:
    external:
      name: webproxy
