version: '3'

services:
  proxy:
    image: traefik:alpine
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    logging:
      options:
        max-size: "4m"
        max-file: "10"

networks:
  default:
    external:
      name: webproxy
